enableGlobalCache: true

logFilters:
  - code: YN0032
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@project-serum/anchor@*":
    dependencies:
      "@juici/case": ^0.1.2
  "@switchboard-xyz/switchboard-v2@*":
    dependencies:
      "@types/big.js": ^6

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
