anchor_version = "0.24.2"

[programs.localnet]
hh_escrow = "Yb4spZYFpgad4pDvV1mdU7pFU9vQWNeDS4degy7eR1u"

[provider]
cluster = "localnet"
wallet = "test_wallet.json"

[scripts]
test = "yarn run jest"
pre_test_deploy = "scripts/test_deploy"
