anchor_version = "0.24.2"

[provider]
cluster = "localnet"
wallet = "test_wallet.json"

[programs.localnet]
hh_escrow = "Yb4spZYFpgad4pDvV1mdU7pFU9vQWNeDS4degy7eR1u"
hyperspace_resolver = "CyX3buQXyW939M5LReVhPGwcTDoPWMAdArehA2aqVRvP"
switchboard_resolver = "8kjTCbyh98kFMDsCkCMUwDj3TNJh4f5fREquiVLUCX2P"

[test.validator]
url = "devnet"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" # Token program
[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" # Associated Token program

# Switchboard devnet accounts
[[test.validator.clone]]
address = "2KgowxogBrGqRcgXQEmqFvC3PGtCu66qERNJevYW8Ajh" # authority
[[test.validator.clone]]
address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt" # program state
[[test.validator.clone]]
address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy" # token vault
[[test.validator.clone]]
address = "94ZVbwgxGiHvi2yngEnU8aqTtyyqqYcy5caQCZeSb4FP" # dao mint
[[test.validator.clone]]
address = "F8ce7MsckeZAbAGmxjJNetxYXQa9mKr9nnrC3qKubyYy" # permissionless queue
[[test.validator.clone]]
address = "7yJ3sSifpmUFB5BcXy6yMDje15xw2CovJjfXfBKsCfT5" # oracle buffer
[[test.validator.clone]]
address = "GN9jjCy2THzZxhYqZETmPM3my8vg4R5JyNkgULddUMa5" # crank #1
