anchor_version = "0.24.2"

[programs.localnet]
hh_escrow = "27yeAvyRBxkiYT2NqZBjJDe4PNRcCxyqVQ1yXBpj2Hjt"

[provider]
cluster = "devnet"
wallet = "devnet-authority"

[scripts]
test = "yarn run jest"
pre_test_deploy = "scripts/test_deploy"
