anchor_version = "0.24.2"

[programs.localnet]
hh_escrow = "27yeAvyRBxkiYT2NqZBjJDe4PNRcCxyqVQ1yXBpj2Hjt"

[provider]
cluster = "localnet"
wallet = "test_wallet.json"

[scripts]
test = "yarn run jest"
pre_test_deploy = "scripts/test_deploy"
