anchor_version = "0.24.2"

[programs.localnet]
hh_escrow = "Yb4spZYFpgad4pDvV1mdU7pFU9vQWNeDS4degy7eR1u"
switchboard_updater = "5CSY8ocw2SAGZMX1aS2qLWoUXXyjgKVhxSC8aGSCkz8W"

[provider]
cluster = "localnet"
wallet = "test_wallet.json"

[scripts]
test = "yarn run jest"
pre_test_deploy = "scripts/test_deploy"
