version: "3.8"

name: switchboard-oracle

services:
  switchboard:
    image: "switchboardlabs/node:dev-v2-10-10-22"
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - LIVE=1
      - CLUSTER=devnet
      - RPC_URL=${RPC_URL}
      - ORACLE_KEY=${ORACLE_KEY}
      - HEARTBEAT_INTERVAL=15

secrets:
  PAYER_SECRETS:
    file: ./test_wallet.json
