[package]
name = "hh-escrow"
version = "0.1.0"
description = "Escrow program for P2P predictions"
edition = "2021"
rust-version = "1.59"

[lib]
crate-type = ["cdylib", "lib"]
name = "hh_escrow"

[features]
default = []

no-entrypoint = []
no-idl = []
no-log-ix-name = []

cpi = ["no-entrypoint"]

[dependencies]
common = { path = "../../libs/common" }

anchor-lang = "0.24.2"
anchor-spl = "0.24.2"
solana-program = "1.9.16"
spl-associated-token-account = { version = "1.0.5", default-features = false }

borsh = { version = "0.9.3", features = ["const-generics"] }
